### ISSUE TITLE
FIGHT!

### ISSUE THREAD

**Issue by bloxain** [SrcSkol/Lightspeed-ChromeFilter#1]
STAND AGAINST LIGHT-SPEED

https://github.com/bloxain/Exposing-Light-Speed

they
key log,
mouse track,
view tabs,

many of your fellow classmates have no idea that passwords may be stolen!

**Comment by SrcSkol** [comment]
I mean i kinda agree with you but y tf would u self-promote in a damn archive repo lmao

**Comment by bloxain** [comment]
its not a self promote i am looking for this that light-speed does that are illeagal
